-- CREATE TABLE IF NOT EXISTS messages (
--     id VARCHAR(60) PRIMARY KEY,
--     text TEXT NOT NULL
-- );

CREATE TABLE IF NOT EXISTS messages (
    id VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    text TEXT NOT NULL
);
